# Generated by Django 3.2.6 on 2021-08-20 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_categoryapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryapi',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoryapi',
            name='posts',
            field=models.ManyToManyField(related_name='api_categories', to='api.PostApi'),
        ),
    ]
