# Generated by Django 3.2.6 on 2021-08-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_categoryapi_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentapi',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commentapi',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postapi',
            name='owner',
        ),
        migrations.DeleteModel(
            name='CategoryApi',
        ),
        migrations.DeleteModel(
            name='CommentApi',
        ),
        migrations.DeleteModel(
            name='PostApi',
        ),
    ]
